openapi: 3.0.0
info:
  title: HemantGPT RAG Chatbot
  version: "1.0"
paths:
  /ask:
    post:
      summary: Ask a question to the RAG chatbot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
              required:
                - question
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string